name: deploy-on-dev

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
   inputs:
        issue-nr:
          description: "issue number"
          required: true

jobs:
  dockerize:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Git Identity
        run: |
          git config --global user.name 'geovbot'
          git config --global user.email 'github.bot@geovistory.org'
          git remote set-url origin https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Install Lerna globally
        run: npm install lerna --global
        
      - name: Show lerna.json 
        run: cat lerna.json
        
      - name: Tag this commit with issue-tag 
        run: lerna version prepatch --preid issue-${{github.event.inputs.issue-nr}} --yes
        env:
           GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           
      - name: Print lerna logs
        if: always()
        run: cat lerna-debug.log
        
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker Build & Push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/geovistory/design-system:issue-${{github.event.inputs.issue-nr}}
